[install:bug] install shared libraries correctly

diff --git a/qt/mac_deploy b/qt/mac_deploy
--- a/qt/mac_deploy
+++ b/qt/mac_deploy
@@ -21,6 +21,12 @@ if [ ! -d "$bundle" ]; then
   exit 1
 fi
 
+install_prefix="$3"
+if [ ! -d "install_prefix" ]; then
+  echo "error: install_prefix directory '$install_prefix' does not exist"
+  exit 1
+fi
+
 # create the proj language directory
 mkdir -p ${bundle}/Contents/Resources/English.lproj
 
@@ -33,7 +39,7 @@ fi
 binarypath="${bundle}/Contents/MacOS/${binary}"
 
 # run macdeployqt
-${qtdir}/bin/macdeployqt ${bundle} -always-overwrite
+${qtdir}/bin/macdeployqt ${bundle} -always-overwrite -libpath=${install_prefix}/lib
 
 # if the final binary references the Qt frameworks via rpath, we need to actually
 # add a relative rpath, since macdeployqt completely ignores this
