[repo:style] enhance linting scripts to ignroe build dirs; lint the scripts them selves
[repo:style] lint shell files

diff --git a/python/fspython b/python/fspython
--- a/python/fspython
+++ b/python/fspython
@@ -8,8 +8,8 @@ export PYTHONPATH="${FREESURFER_HOME}/python/packages:$PYTHONPATH"
 
 # run python
 if [ -e "${FREESURFER_HOME}/python/bin/python3" ]; then
-    exec ${FREESURFER_HOME}/python/bin/python3 "$@"
+  exec ${FREESURFER_HOME}/python/bin/python3 "$@"
 else
-    echo "error: fspython has not been configured correctly - \$FREESURFER_HOME/python/bin/python3 does not exist"
-    exit 1
+  echo "error: fspython has not been configured correctly - \$FREESURFER_HOME/python/bin/python3 does not exist"
+  exit 1
 fi
diff --git a/scripts/bedpostx_mgh b/scripts/bedpostx_mgh
--- a/scripts/bedpostx_mgh
+++ b/scripts/bedpostx_mgh
@@ -8,20 +8,20 @@
 #   Part of FSL - FMRIB's Software Library
 #   http://www.fmrib.ox.ac.uk/fsl
 #   fsl@fmrib.ox.ac.uk
-#   
+#
 #   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
 #   Imaging of the Brain), Department of Clinical Neurology, Oxford
 #   University, Oxford, UK
-#   
-#   
+#
+#
 #   LICENCE
-#   
+#
 #   FMRIB Software Library, Release 4.0 (c) 2007, The University of
 #   Oxford (the "Software")
-#   
+#
 #   The Software remains the property of the University of Oxford ("the
 #   University").
-#   
+#
 #   The Software is distributed "AS IS" under this Licence solely for
 #   non-commercial use in the hope that it will be useful, but in order
 #   that the University as a charitable foundation protects its assets for
@@ -33,13 +33,13 @@
 #   all responsibility for the use which is made of the Software. It
 #   further disclaims any liability for the outcomes arising from using
 #   the Software.
-#   
+#
 #   The Licensee agrees to indemnify the University and hold the
 #   University harmless from and against any and all claims, damages and
 #   liabilities asserted by third parties (including claims for
 #   negligence) which arise directly or indirectly from the use of the
 #   Software or the sale of any products based on the Software.
-#   
+#
 #   No part of the Software may be reproduced, modified, transmitted or
 #   transferred in any form or by any means, electronic or mechanical,
 #   without the express permission of the University. The permission of
@@ -50,7 +50,7 @@
 #   transmitted product. You may be held legally responsible for any
 #   copyright infringement that is caused or encouraged by your failure to
 #   abide by these terms and conditions.
-#   
+#
 #   You are not permitted under this Licence to use this Software
 #   commercially. Use for which any financial return is received shall be
 #   defined as commercial use, and includes (1) integration of all or part
@@ -67,107 +67,106 @@
 #   University, to negotiate a licence. Contact details are:
 #   innovation@isis.ox.ac.uk quoting reference DE/1112.
 
-BPDIR=`dirname $0`
+BPDIR=$(dirname $0)
 
-if [ "x$SGE_ROOT" = "x" ] ; then
-    if [ -f /usr/local/share/sge/default/common/settings.sh ] ; then
-	. /usr/local/share/sge/default/common/settings.sh
-    elif [ -f /usr/local/sge/default/common/settings.sh ] ; then
-	. /usr/local/sge/default/common/settings.sh
-    fi
+if [ "x$SGE_ROOT" = "x" ]; then
+  if [ -f /usr/local/share/sge/default/common/settings.sh ]; then
+    . /usr/local/share/sge/default/common/settings.sh
+  elif [ -f /usr/local/sge/default/common/settings.sh ]; then
+    . /usr/local/sge/default/common/settings.sh
+  fi
 fi
 
 # Check if this is being run on PBS but isn't a job itself (AY)
-if [ -d /pbs ] && [ -z $PBS_JOBID ] ; then
-    dopbsjobs=1;
+if [ -d /pbs ] && [ -z $PBS_JOBID ]; then
+  dopbsjobs=1
 else
-    dopbsjobs=0;
+  dopbsjobs=0
 fi
 
-
 Usage() {
-    echo ""
-    echo "Usage: bedpostx_mgh <subject directory> [options] ..."
-    echo ""
-    echo "expects to find bvals and bvecs in subject directory"
-    echo "expects to find data and nodif_brain_mask in subject directory"
-    echo "options (old syntax)"
-    echo "-n (number of fibres per voxel, default 2)"
-    echo "-w (ARD weight, more weight means less secondary fibres per voxel, default 1)"
-    echo "-b (burnin period, default 1000)"
-    echo "-j (number of jumps, default 1250)"
-    echo "-s (sample every, default 25)"
-    echo ""
-    echo ""
-    echo "ALTERNATIVELY: you can pass on xfibres options onto directly bedpostx"
-    echo " For example:  bedpostx <subject directory> --noard --cnonlinear"
-    echo " Type 'xfibres --help' for a list of available options "
-    echo " Default options will be bedpostx default (see above), and not xfibres default."
-    echo ""
-    echo "Note: Use EITHER old OR new syntax."
-    echo ""
-    echo "This is a modified version of FSL's bedpostx that is compatible with"
-    echo "the PBS queueing system running on launchpad/seychelles and can be"
-    echo "used by Martinos Center users to parallelize computation."
-    echo ""
-    echo "This script runs the exact same algorithm as bedpostx, but it submits"
-    echo "the processing for each slice as a separate PBS job. Thus, bedpostx"
-    echo "and bedpostx_mgh will give you the same result, but the former will"
-    echo "do it in days and the latter in hours."
-    echo ""
-    echo "Command line options and the structure of the input directory are the"
-    echo "same as for the original bedpostx."
-    echo ""
-    echo "Do not submit bedpostx_mgh as a job on launchpad/seychelles. Run it"
-    echo "directly at the launchpad/seychelles prompt and it will submit the"
-    echo "jobs for you. Note that this will generate a large number of jobs, so"
-    echo "don't launch it on more than one data set at the same time. You may"
-    echo "get some PBS emails about jobs being held that you have to release -"
-    echo "you can ignore these emails as the script will take care of that."
-    exit 1
+  echo ""
+  echo "Usage: bedpostx_mgh <subject directory> [options] ..."
+  echo ""
+  echo "expects to find bvals and bvecs in subject directory"
+  echo "expects to find data and nodif_brain_mask in subject directory"
+  echo "options (old syntax)"
+  echo "-n (number of fibres per voxel, default 2)"
+  echo "-w (ARD weight, more weight means less secondary fibres per voxel, default 1)"
+  echo "-b (burnin period, default 1000)"
+  echo "-j (number of jumps, default 1250)"
+  echo "-s (sample every, default 25)"
+  echo ""
+  echo ""
+  echo "ALTERNATIVELY: you can pass on xfibres options onto directly bedpostx"
+  echo " For example:  bedpostx <subject directory> --noard --cnonlinear"
+  echo " Type 'xfibres --help' for a list of available options "
+  echo " Default options will be bedpostx default (see above), and not xfibres default."
+  echo ""
+  echo "Note: Use EITHER old OR new syntax."
+  echo ""
+  echo "This is a modified version of FSL's bedpostx that is compatible with"
+  echo "the PBS queueing system running on launchpad/seychelles and can be"
+  echo "used by Martinos Center users to parallelize computation."
+  echo ""
+  echo "This script runs the exact same algorithm as bedpostx, but it submits"
+  echo "the processing for each slice as a separate PBS job. Thus, bedpostx"
+  echo "and bedpostx_mgh will give you the same result, but the former will"
+  echo "do it in days and the latter in hours."
+  echo ""
+  echo "Command line options and the structure of the input directory are the"
+  echo "same as for the original bedpostx."
+  echo ""
+  echo "Do not submit bedpostx_mgh as a job on launchpad/seychelles. Run it"
+  echo "directly at the launchpad/seychelles prompt and it will submit the"
+  echo "jobs for you. Note that this will generate a large number of jobs, so"
+  echo "don't launch it on more than one data set at the same time. You may"
+  echo "get some PBS emails about jobs being held that you have to release -"
+  echo "you can ignore these emails as the script will take care of that."
+  exit 1
 }
 
 # Find FSL version (AY)
-fslver=(`cat $FSLDIR/etc/fslversion | sed 's/\./ /g'`)
+fslver=($(cat $FSLDIR/etc/fslversion | sed 's/\./ /g'))
 if [ -z ${fslver[1]} ]; then fslver[1]=0; fi
 if [ -z ${fslver[2]} ]; then fslver[2]=0; fi
 
 # The order of bedpostx_single_slice arguments has been shifting around
 # in different versions of FSL
 if [ ${fslver[0]} -lt 4 ]; then
-    echo "Unsupported FSL version (${fslver[0]}.${fslver[1]}.${fslver[2]})"
-    exit 1
+  echo "Unsupported FSL version (${fslver[0]}.${fslver[1]}.${fslver[2]})"
+  exit 1
 else
-    if [ ${fslver[0]} -eq 4 ] && [ ${fslver[1]} -eq 0 ]; then
-	if [ ${fslver[2]} -lt 2 ]; then
-	    argorder=400;				# Order as in FSL 4.0.0
-	else
-            argorder=402;				# Order as in FSL 4.0.2
-	fi
-    elif [ ${fslver[0]} -eq 4 ] && [ ${fslver[1]} -eq 1 ]; then
-	if [ ${fslver[2]} -lt 5 ]; then
-	    argorder=402;				# Order as in FSL 4.0.2
-	elif [ ${fslver[2]} -lt 9 ]; then
-	    argorder=415;				# Order as in FSL 4.1.5
-	else
-            argorder=419;				# Order as in FSL 4.1.9
-	fi
+  if [ ${fslver[0]} -eq 4 ] && [ ${fslver[1]} -eq 0 ]; then
+    if [ ${fslver[2]} -lt 2 ]; then
+      argorder=400 # Order as in FSL 4.0.0
     else
-	argorder=419;					# Order as in FSL 4.1.9
+      argorder=402 # Order as in FSL 4.0.2
     fi
+  elif [ ${fslver[0]} -eq 4 ] && [ ${fslver[1]} -eq 1 ]; then
+    if [ ${fslver[2]} -lt 5 ]; then
+      argorder=402 # Order as in FSL 4.0.2
+    elif [ ${fslver[2]} -lt 9 ]; then
+      argorder=415 # Order as in FSL 4.1.5
+    else
+      argorder=419 # Order as in FSL 4.1.9
+    fi
+  else
+    argorder=419 # Order as in FSL 4.1.9
+  fi
 fi
 
-make_absolute(){
-    dir=$1;
-    if [ -d ${dir} ]; then
-	OLDWD=`pwd`
-	cd ${dir}
-	dir_all=`pwd`
-	cd $OLDWD
-    else
-	dir_all=${dir}
-    fi
-    echo ${dir_all}
+make_absolute() {
+  dir=$1
+  if [ -d ${dir} ]; then
+    OLDWD=$(pwd)
+    cd ${dir}
+    dir_all=$(pwd)
+    cd $OLDWD
+  else
+    dir_all=${dir}
+  fi
+  echo ${dir_all}
 }
 
 [ "$1" = "" ] && Usage
@@ -180,19 +179,36 @@ njumps=1250
 sampleevery=25
 model=1
 
-while [ ! -z "$1" ]
-do
-  if [ -d "$1" ]; then		# Allow multiple input directories (AY)
+while [ ! -z "$1" ]; do
+  if [ -d "$1" ]; then # Allow multiple input directories (AY)
     dirlist="$dirlist $1"
   else
     case "$1" in
-        -n) nfibres=$2;shift;;
-        -w) fudge=$2;shift;;
-        -b) burnin=$2;shift;;
-        -j) njumps=$2;shift;;
-        -s) sampleevery=$2;shift;;
-        -model) model=$2;shift;;
-        *) break;;
+      -n)
+        nfibres=$2
+        shift
+        ;;
+      -w)
+        fudge=$2
+        shift
+        ;;
+      -b)
+        burnin=$2
+        shift
+        ;;
+      -j)
+        njumps=$2
+        shift
+        ;;
+      -s)
+        sampleevery=$2
+        shift
+        ;;
+      -model)
+        model=$2
+        shift
+        ;;
+      *) break ;;
     esac
   fi
   shift
@@ -204,63 +220,63 @@ opts="$opts $defopts $*"
 # Process multiple input directories, queue them up serially (AY)
 for subjdir in $dirlist; do
 
-subjdir=`make_absolute $subjdir`
-subjdir=`echo $subjdir | sed 's/\/$/$/g'`
+  subjdir=$(make_absolute $subjdir)
+  subjdir=$(echo $subjdir | sed 's/\/$/$/g')
 
-echo subjectdir is $subjdir
+  echo subjectdir is $subjdir
 
-#check that all required files exist
+  #check that all required files exist
 
-if [ ! -d $subjdir ]; then
-	echo "subject directory $1 not found"
-	exit 1
-fi
+  if [ ! -d $subjdir ]; then
+    echo "subject directory $1 not found"
+    exit 1
+  fi
 
-if [ ! -e ${subjdir}/bvecs ]; then
-	echo "${subjdir}/bvecs not found"
-	exit 1
-fi
+  if [ ! -e ${subjdir}/bvecs ]; then
+    echo "${subjdir}/bvecs not found"
+    exit 1
+  fi
 
-if [ ! -e ${subjdir}/bvals ]; then
-	echo "${subjdir}/bvals not found"
-	exit 1
-fi
+  if [ ! -e ${subjdir}/bvals ]; then
+    echo "${subjdir}/bvals not found"
+    exit 1
+  fi
 
-if [ `${FSLDIR}/bin/imtest ${subjdir}/data` -eq 0 ]; then
-	echo "${subjdir}/data not found"
-	exit 1
-fi
+  if [ $(${FSLDIR}/bin/imtest ${subjdir}/data) -eq 0 ]; then
+    echo "${subjdir}/data not found"
+    exit 1
+  fi
 
-if [ `${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask` -eq 0 ]; then
-	echo "${subjdir}/nodif_brain_mask not found"
-	exit 1
-fi
+  if [ $(${FSLDIR}/bin/imtest ${subjdir}/nodif_brain_mask) -eq 0 ]; then
+    echo "${subjdir}/nodif_brain_mask not found"
+    exit 1
+  fi
 
-echo Making bedpostx directory structure
+  echo Making bedpostx directory structure
 
-mkdir -p ${subjdir}.bedpostX/
-mkdir -p ${subjdir}.bedpostX/diff_slices
-mkdir -p ${subjdir}.bedpostX/logs
-mkdir -p ${subjdir}.bedpostX/logs/pid_${$}
-mkdir -p ${subjdir}.bedpostX/xfms
+  mkdir -p ${subjdir}.bedpostX/
+  mkdir -p ${subjdir}.bedpostX/diff_slices
+  mkdir -p ${subjdir}.bedpostX/logs
+  mkdir -p ${subjdir}.bedpostX/logs/pid_${$}
+  mkdir -p ${subjdir}.bedpostX/xfms
 
-mailto=`whoami`
-echo Queuing preprocessing stages
-if [ "x$mergeid" = "x" ] ; then
-    preprocid=`${BPDIR}/fsl_sub_mgh -T 60 -m a -N bedpostx_pre -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostx_preproc.sh ${subjdir}`
-else
-    preprocid=`${BPDIR}/fsl_sub_mgh -j $mergeid -T 60 -m a -N bedpostx_pre -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostx_preproc.sh ${subjdir}`
-fi
+  mailto=$(whoami)
+  echo Queuing preprocessing stages
+  if [ "x$mergeid" = "x" ]; then
+    preprocid=$(${BPDIR}/fsl_sub_mgh -T 60 -m a -N bedpostx_pre -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostx_preproc.sh ${subjdir})
+  else
+    preprocid=$(${BPDIR}/fsl_sub_mgh -j $mergeid -T 60 -m a -N bedpostx_pre -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostx_preproc.sh ${subjdir})
+  fi
 
-echo Queuing parallel processing stage
-nslices=`${FSLDIR}/bin/fslval ${subjdir}/data dim3`
-[ -f ${subjdir}.bedpostX/commands.txt ] && rm ${subjdir}.bedpostX/commands.txt
-if [ "x$SGE_ROOT" = "x" ] && [ $dopbsjobs -eq 0 ]; then
+  echo Queuing parallel processing stage
+  nslices=$(${FSLDIR}/bin/fslval ${subjdir}/data dim3)
+  [ -f ${subjdir}.bedpostX/commands.txt ] && rm ${subjdir}.bedpostX/commands.txt
+  if [ "x$SGE_ROOT" = "x" ] && [ $dopbsjobs -eq 0 ]; then
 
-# 
-# Need to set off a backgrounded monitoring task
-# 
-    cat <<EOM > ${subjdir}.bedpostX/monitor
+    #
+    # Need to set off a backgrounded monitoring task
+    #
+    cat <<EOM >${subjdir}.bedpostX/monitor
 #!/bin/sh
 finished=0
 logdir=${subjdir}.bedpostX/logs
@@ -310,44 +326,43 @@ done
 exit_test
 EOM
     chmod +x ${subjdir}.bedpostX/monitor
-    ${subjdir}.bedpostX/monitor&
+    ${subjdir}.bedpostX/monitor &
     monitorpid=$!
-fi
-slice=0
-while [ $slice -lt $nslices ]
-do
-    slicezp=`$FSLDIR/bin/zeropad $slice 4`
-    if [ `$FSLDIR/bin/imtest ${subjdir}.bedpostX/diff_slices/data_slice_$slicezp/dyads1` -eq 1 ];then
-	echo "slice $slice has already been processed"
+  fi
+  slice=0
+  while [ $slice -lt $nslices ]; do
+    slicezp=$($FSLDIR/bin/zeropad $slice 4)
+    if [ $($FSLDIR/bin/imtest ${subjdir}.bedpostX/diff_slices/data_slice_$slicezp/dyads1) -eq 1 ]; then
+      echo "slice $slice has already been processed"
     else
-	if [ $argorder -eq 400 ]; then
-	    echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $nfibres $fudge $burnin $slice" \
-	      >> ${subjdir}.bedpostX/commands.txt
-	elif [ $argorder -eq 402 ]; then
-	    echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $nfibres $fudge $burnin $njumps $sampleevery $slice" \
-	      >> ${subjdir}.bedpostX/commands.txt
-	elif [ $argorder -eq 415 ]; then
-	    echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $nfibres $fudge $burnin $njumps $sampleevery $model $slice" \
-	      >> ${subjdir}.bedpostX/commands.txt
-	elif [ $argorder -eq 419 ]; then
-	    echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $slice $opts" \
-	      >> ${subjdir}.bedpostX/commands.txt
-	fi
+      if [ $argorder -eq 400 ]; then
+        echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $nfibres $fudge $burnin $slice" \
+          >>${subjdir}.bedpostX/commands.txt
+      elif [ $argorder -eq 402 ]; then
+        echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $nfibres $fudge $burnin $njumps $sampleevery $slice" \
+          >>${subjdir}.bedpostX/commands.txt
+      elif [ $argorder -eq 415 ]; then
+        echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $nfibres $fudge $burnin $njumps $sampleevery $model $slice" \
+          >>${subjdir}.bedpostX/commands.txt
+      elif [ $argorder -eq 419 ]; then
+        echo "${FSLDIR}/bin/bedpostx_single_slice.sh $subjdir $slice $opts" \
+          >>${subjdir}.bedpostX/commands.txt
+      fi
     fi
     slice=$(($slice + 1))
-done
+  done
 
-bedpostid=`${BPDIR}/fsl_sub_mgh -j $preprocid -l ${subjdir}.bedpostX/logs -m a -N bedpostx -t ${subjdir}.bedpostX/commands.txt`
+  bedpostid=$(${BPDIR}/fsl_sub_mgh -j $preprocid -l ${subjdir}.bedpostX/logs -m a -N bedpostx -t ${subjdir}.bedpostX/commands.txt)
 
-echo Queuing post processing stage
-mergeid=`${BPDIR}/fsl_sub_mgh -j $bedpostid -T 60 -m ae -N bedpostx_post -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostx_postproc.sh $subjdir`
+  echo Queuing post processing stage
+  mergeid=$(${BPDIR}/fsl_sub_mgh -j $bedpostid -T 60 -m ae -N bedpostx_post -l ${subjdir}.bedpostX/logs ${FSLDIR}/bin/bedpostx_postproc.sh $subjdir)
 
-[ "x$SGE_ROOT" = "x" ] && [ $dopbsjobs -eq 0 ] && kill $monitorpid
+  [ "x$SGE_ROOT" = "x" ] && [ $dopbsjobs -eq 0 ] && kill $monitorpid
 
-if [ "x$SGE_ROOT" != "x" ]; then
+  if [ "x$SGE_ROOT" != "x" ]; then
     echo
     echo Type ${subjdir}.bedpostX/monitor to show progress.
-    cat <<EOM > ${subjdir}.bedpostX/monitor
+    cat <<EOM >${subjdir}.bedpostX/monitor
 #!/bin/sh
 finished=0
 logdir=${subjdir}.bedpostX/logs
@@ -375,7 +390,7 @@ EOM
     chmod +x ${subjdir}.bedpostX/monitor
 
     echo Type ${subjdir}.bedpostX/cancel to terminate all the queued tasks.
-    cat <<EOC > ${subjdir}.bedpostX/cancel
+    cat <<EOC >${subjdir}.bedpostX/cancel
 #!/bin/sh
 qdel $mergeid $bedpostid $preprocid
 EOC
@@ -384,10 +399,10 @@ EOC
     echo
     echo You will get an email at the end of the post-processing stage.
     echo
-elif [ $dopbsjobs -eq 1 ] ; then
+  elif [ $dopbsjobs -eq 1 ]; then
     echo
-    echo Type ${subjdir}.bedpostX/monitor on `hostname` to show progress.
-    cat <<EOM > ${subjdir}.bedpostX/monitor
+    echo Type ${subjdir}.bedpostX/monitor on $(hostname) to show progress.
+    cat <<EOM >${subjdir}.bedpostX/monitor
 #!/bin/sh
 finished=0
 logdir=${subjdir}.bedpostX/logs
@@ -407,8 +422,8 @@ done
 EOM
     chmod +x ${subjdir}.bedpostX/monitor
 
-    echo Type ${subjdir}.bedpostX/cputime on `hostname` to show CPU time of completed jobs.
-    cat <<EOT > ${subjdir}.bedpostX/cputime
+    echo Type ${subjdir}.bedpostX/cputime on $(hostname) to show CPU time of completed jobs.
+    cat <<EOT >${subjdir}.bedpostX/cputime
 #!/bin/sh
 logdir=${subjdir}.bedpostX/logs
 for jobname in \`cat \$logdir/joblist | awk '{print \$1}' | sort\` ; do
@@ -421,8 +436,8 @@ done
 EOT
     chmod +x ${subjdir}.bedpostX/cputime
 
-    echo Type ${subjdir}.bedpostX/cancel on `hostname` to terminate all the queued tasks.
-    cat <<EOC > ${subjdir}.bedpostX/cancel
+    echo Type ${subjdir}.bedpostX/cancel on $(hostname) to terminate all the queued tasks.
+    cat <<EOC >${subjdir}.bedpostX/cancel
 #!/bin/sh
 logdir=${subjdir}.bedpostX/logs
 qdel $mergeid \`sort -r \$logdir/joblist | awk '{printf \$2 " "}'\` $preprocid
@@ -432,8 +447,7 @@ EOC
     echo
     echo You will get an email at the end of the post-processing stage.
     echo
-fi
+  fi
 
-# Process multiple input directories, queue them up serially (AY)
+  # Process multiple input directories, queue them up serially (AY)
 done
-
diff --git a/scripts/fs_lib_check b/scripts/fs_lib_check
--- a/scripts/fs_lib_check
+++ b/scripts/fs_lib_check
@@ -86,76 +86,78 @@ G_SYNOPSIS="
 "
 SELF=$(basename $0)
 
-function synopsis_show
-{
-	echo "USAGE:"
-	echo "$G_SYNOPSIS"
+function synopsis_show() {
+  echo "USAGE:"
+  echo "$G_SYNOPSIS"
 }
 
-function ret_check
-{
-	# ARGS
-	# $1 		in		return value to check
-	#
-	# DESC
-	# Checks for the passed return value, and echoes a
-	# conditional to stdout. Returns this value back to
-	# the caller.
-	#
+function ret_check() {
+  # ARGS
+  # $1 		in		return value to check
+  #
+  # DESC
+  # Checks for the passed return value, and echoes a
+  # conditional to stdout. Returns this value back to
+  # the caller.
+  #
 
-	local ret=$1
+  local ret=$1
 
-	echo -en "\t\t\t"
-	if [[ $ret != "0" ]] ; then
-		echo -e "[ failure ]"
-	else
-		echo -e "[ ok ]"
-	fi
-	return $ret
+  echo -en "\t\t\t"
+  if [[ $ret != "0" ]]; then
+    echo -e "[ failure ]"
+  else
+    echo -e "[ ok ]"
+  fi
+  return $ret
 }
 
-function die
-{
-	#
-	# ARGS
-	# $1		in		action
-	# $2		in		msg
-	# $3 		in		exit code
-	#
-	# DESC
-	# Exit to system with descriptive text and error code.
-	#
+function die() {
+  #
+  # ARGS
+  # $1		in		action
+  # $2		in		msg
+  # $3 		in		exit code
+  #
+  # DESC
+  # Exit to system with descriptive text and error code.
+  #
 
-	local action="$1"
-	local msg="$2"
-	local exitCode="$3"
+  local action="$1"
+  local msg="$2"
+  local exitCode="$3"
 
-	printf "\n\tWhile $action\n"
-	printf "\t$msg\n"
-	printf "\tExiting with code '$exitCode'.\n\n"
-	exit $exitCode
+  printf "\n\tWhile $action\n"
+  printf "\t$msg\n"
+  printf "\tExiting with code '$exitCode'.\n\n"
+  exit $exitCode
 }
-
 
 # Is this an rpm system?
-if [[ -d /etc/rpm ]] ; then
-	b_RPM=1
+if [[ -d /etc/rpm ]]; then
+  b_RPM=1
 else
-	b_RPM=0
+  b_RPM=0
 fi
 
-while getopts vhlr option ; do
-	case "$option"
-	in
-		l) b_RPM=0 ;;
-		r) b_RPM=1 ;;
-		v) printf "$SELF, version = $G_ID\n"
-		    exit 0;;
-		h) synopsis_show
-		    exit 0;;
-		\?) synopsis_show
-		    exit 0;;
-	esac
+while getopts vhlr option; do
+  case "$option" in
+
+    l) b_RPM=0 ;;
+    r) b_RPM=1 ;;
+    v)
+      printf "$SELF, version = $G_ID\n"
+      exit 0
+      ;;
+    h)
+      synopsis_show
+      exit 0
+      ;;
+    \?)
+      synopsis_show
+      exit 0
+      ;;
+  esac
 done
 
 # Is this a Linux system?
@@ -164,49 +166,47 @@ b_LINUX=$(uname -a | grep -i Linux | wc -l)
 # Is this a Darwin system?
 b_DARWIN=$(uname -a | grep -i Darwin | wc -l)
 
-if (( !b_LINUX )) ; then
-	die "checking system, a non-Linux OS was found."	\
-		 "This script will only work on Linux systems."	\
-		1
+if ((!b_LINUX)); then
+  die "checking system, a non-Linux OS was found." \
+    "This script will only work on Linux systems." \
+    1
 fi
 
-if (( b_RPM )) ; then
-	# Check for 'rpm' executable
-	b_RPMexe=$(type -all rpm 2>/dev/null | awk '{print $3}' | wc -l)
-	if (( !b_RPMexe )) ; then
-		die "checking for rpm executable,"			\
-			"no file called 'rpm' was found on path." 3
-	fi
+if ((b_RPM)); then
+  # Check for 'rpm' executable
+  b_RPMexe=$(type -all rpm 2>/dev/null | awk '{print $3}' | wc -l)
+  if ((!b_RPMexe)); then
+    die "checking for rpm executable," \
+      "no file called 'rpm' was found on path." 3
+  fi
 fi
 
 # Now perform the lib check
-if (( b_LINUX && b_RPM )) ; then
-	CHKCMDPREFIX="rpm -qa | grep -i "
-	FSLIBLIST="jpeg tiff tcl-8 tk-8 tix-8 blt glut"
-	TRIGGER="rpm package "
+if ((b_LINUX && b_RPM)); then
+  CHKCMDPREFIX="rpm -qa | grep -i "
+  FSLIBLIST="jpeg tiff tcl-8 tk-8 tix-8 blt glut"
+  TRIGGER="rpm package "
 fi
 
-if (( b_LINUX && !b_RPM )) ; then
-	CHKCMDPREFIX="ldconfig -p | grep lib"
-	FSLIBLIST="jpeg tiff tcl8 tk8 tix8 BLT glut"
-	TRIGGER="lib"
+if ((b_LINUX && !b_RPM)); then
+  CHKCMDPREFIX="ldconfig -p | grep lib"
+  FSLIBLIST="jpeg tiff tcl8 tk8 tix8 BLT glut"
+  TRIGGER="lib"
 fi
 
 printf "\n%48s\n\n" "FreeSurfer library check"
 
-for LIB in $FSLIBLIST ; do
-	printf "%-40s" "checking for ${TRIGGER}$LIB..."
-	CHKCMD="${CHKCMDPREFIX}${LIB}"
-	eval $CHKCMD 2>/dev/null >/dev/null
-        ret_check $? || \
-		die "checking for ${TRIGGER}$LIB," \
-			"the library/package does not seem to exist on your system." \
-			2
+for LIB in $FSLIBLIST; do
+  printf "%-40s" "checking for ${TRIGGER}$LIB..."
+  CHKCMD="${CHKCMDPREFIX}${LIB}"
+  eval $CHKCMD 2>/dev/null >/dev/null
+  ret_check $? ||
+    die "checking for ${TRIGGER}$LIB," \
+      "the library/package does not seem to exist on your system." \
+      2
 done
 
 printf "\n\t%35s\n" "Congratulations!"
 printf "\tAll necessary libs for running FreeSurfer were found.\n\n"
 
 exit 0
-
-
diff --git a/scripts/listsubj b/scripts/listsubj
--- a/scripts/listsubj
+++ b/scripts/listsubj
@@ -1,8 +1,7 @@
 #!/bin/bash
 
-function help_exit
-{
-    cat <<-EOF
+function help_exit() {
+  cat <<-EOF
 List subject IDs in SUBJECT_DIR.
 Usage: $(basename $0) [OPTIONS] SUBJECT_DIR
 
@@ -18,72 +17,71 @@ Options:
     -h, --help          Show this help text
 
 EOF
-    exit 0
+  exit 0
 }
 
-function err_exit
-{
-    echo "ERROR: $@" && exit 1
+function err_exit() {
+  echo "ERROR: $@" && exit 1
 }
 
 # Parse arguments.
 [[ $# -eq 0 ]] && help_exit
 positional=()
 while [[ $# -gt 0 ]]; do
-    case "$1" in
-        -c|--cross)
-            stream="c" && shift
-        ;;
-        -b|--base)
-            stream="b" && shift
-        ;;
-        -l|--long)
-            stream="l" && shift
-        ;;
-        -d|--done)
-            state="d" && shift
-        ;;
-        -e|--error)
-            state="e" && shift
-        ;;
-        -r|--running)
-            state="r" && shift
-        ;;
-        -f|--full-path)
-            full_path=1 && shift
-        ;;
-        -n|--count)
-            count=1 && shift
-        ;;
-        -h|--help)
-            help_exit
-        ;;
-        -*)
-            err_exit "unknown flag \"$1\""
-        ;;
-        *)
-            positional+=("$1") && shift
-        ;;
-    esac
+  case "$1" in
+    -c | --cross)
+      stream="c" && shift
+      ;;
+    -b | --base)
+      stream="b" && shift
+      ;;
+    -l | --long)
+      stream="l" && shift
+      ;;
+    -d | --done)
+      state="d" && shift
+      ;;
+    -e | --error)
+      state="e" && shift
+      ;;
+    -r | --running)
+      state="r" && shift
+      ;;
+    -f | --full-path)
+      full_path=1 && shift
+      ;;
+    -n | --count)
+      count=1 && shift
+      ;;
+    -h | --help)
+      help_exit
+      ;;
+    -*)
+      err_exit "unknown flag \"$1\""
+      ;;
+    *)
+      positional+=("$1") && shift
+      ;;
+  esac
 done
-set -- "${positional[@]}" 
+set -- "${positional[@]}"
 sd=$(echo "$1" | sed -e 's,/\+$,,') # Trailing slashes.
 if [[ $# -ne 1 ]]; then
-    err_exit "number of positional arguments is not 1"
+  err_exit "number of positional arguments is not 1"
 elif [[ ! -d $sd ]]; then
-    err_exit "SUBJECTS_DIR \"$sd\" not found"
+  err_exit "SUBJECTS_DIR \"$sd\" not found"
 fi
 
 # Find subjects processed with stream.
 cmd="find \"$sd/\" -mindepth 1 -maxdepth 1 ! -type f ! -name fsaverage"
 if [[ -z $stream ]]; then
-    cmd="$cmd -exec test -e '{}/mri/orig' \; -print"
+  cmd="$cmd -exec test -e '{}/mri/orig' \; -print"
 elif [[ $stream == c ]]; then
-    cmd="$cmd -exec test -e '{}/mri/orig/001.mgz' \; -print"
+  cmd="$cmd -exec test -e '{}/mri/orig/001.mgz' \; -print"
 elif [[ $stream == b ]]; then
-    cmd="$cmd -exec test -e '{}/base-tps' \; -print"
+  cmd="$cmd -exec test -e '{}/base-tps' \; -print"
 elif [[ $stream == l ]]; then
-    cmd="$cmd -name '*.long.*'"
+  cmd="$cmd -name '*.long.*'"
 fi
 subj=$(eval $cmd)
 
@@ -91,22 +89,21 @@ subj=$(eval $cmd)
 [[ -n $full_path ]] && path=$(cd "$sd" && pwd -P)/
 out=()
 for s in $subj; do
-    d="$s/scripts"
-    if [[ $state == d && ! -e "$d/recon-all.done" ]]; then
-        continue
-    elif [[ $state == e && ! -e "$d/recon-all.error" ]]; then
-        continue
-    elif [[ $state == r && ! -e "$d/IsRunning.lh" && \
-            ! -e "$d/IsRunning.rh" ]]; then
-        continue
-    fi
-    out+=("${path}${s##*/}") # Basename only.
+  d="$s/scripts"
+  if [[ $state == d && ! -e "$d/recon-all.done" ]]; then
+    continue
+  elif [[ $state == e && ! -e "$d/recon-all.error" ]]; then
+    continue
+  elif [[ $state == r && ! -e "$d/IsRunning.lh" && ! -e \
+    "$d/IsRunning.rh" ]]; then
+    continue
+  fi
+  out+=("${path}${s##*/}") # Basename only.
 done
 
 # Print output.
 if [[ -n $count ]]; then
-    echo ${#out[@]}
+  echo ${#out[@]}
 else
-    printf '%s\n' "${out[@]}"
+  printf '%s\n' "${out[@]}"
 fi
-
diff --git a/scripts/map_to_base b/scripts/map_to_base
--- a/scripts/map_to_base
+++ b/scripts/map_to_base
@@ -3,7 +3,7 @@
 #
 # map_to_base
 #
-# maps an input image or surface to the base space 
+# maps an input image or surface to the base space
 #
 # Original Author: Martin Reuter
 # CVS Revision Info:
@@ -23,38 +23,36 @@
 #
 #
 
-VERSION='$Id: map_to_base,v 1.4 2011/03/02 20:16:39 nicks Exp $';
+VERSION='$Id: map_to_base,v 1.4 2011/03/02 20:16:39 nicks Exp $'
 
 # WITHOUT FREESURFER DO NOTHING
-if [ -z $FREESURFER_HOME ]
-then
+if [ -z $FREESURFER_HOME ]; then
   echo "ERROR: environment variable FREESURFER_HOME not set"
-  exit 1;
+  exit 1
 fi
 
 # USAGE
-if [ "$#" -le "3" ]
-then
+if [ "$#" -le "3" ]; then
   echo
-	echo "`basename $0` baseid tpid input rt [cross]"
-	echo
-	echo "  baseid:    id of base"
-	echo "  tpid  :    id of tp (without .long.baseid)"
-	echo "  input :    input image, e.g. norm.mgz, aseg.mgz, lh.white"
-	echo "  rt    :    resample-type "
-	echo "               'interpolate' for norm, T1, orig.."
-	echo "               'nearest'     for aseg .."
-	echo "               'surface'     for surfaces .."
-	echo "  cross :    if '1' input from cross sectionals"
-	echo "             default: use longitudinal directories"
-	echo
-	echo " Will map single image or surface from tp dir (cross or long)"
-	echo " to the base space and place output in base dir."
-	echo
-	echo " Output will be in base/mri directory or base/surf"
-	echo " Naming will be: tpid-long.input or tpid-cross.input"
-	echo
-	exit 1
+  echo "$(basename $0) baseid tpid input rt [cross]"
+  echo
+  echo "  baseid:    id of base"
+  echo "  tpid  :    id of tp (without .long.baseid)"
+  echo "  input :    input image, e.g. norm.mgz, aseg.mgz, lh.white"
+  echo "  rt    :    resample-type "
+  echo "               'interpolate' for norm, T1, orig.."
+  echo "               'nearest'     for aseg .."
+  echo "               'surface'     for surfaces .."
+  echo "  cross :    if '1' input from cross sectionals"
+  echo "             default: use longitudinal directories"
+  echo
+  echo " Will map single image or surface from tp dir (cross or long)"
+  echo " to the base space and place output in base dir."
+  echo
+  echo " Output will be in base/mri directory or base/surf"
+  echo " Naming will be: tpid-long.input or tpid-cross.input"
+  echo
+  exit 1
 fi
 
 # SET PARAMETERS
@@ -63,50 +61,55 @@ tp=$2
 input=$3
 rt=$4
 ldir=mri
-if [ "$rt" == "surface" ] ; then ldir=surf ; fi
+if [ "$rt" == "surface" ]; then ldir=surf; fi
 
 long=1
 tpid=$tp.long.$base
 longtxt="-long"
-if [ "$#" -ge "5" ] ; then long=0; tpid=$tp ; longtxt="-cross"; fi
+if [ "$#" -ge "5" ]; then
+  long=0
+  tpid=$tp
+  longtxt="-cross"
+fi
 
 # check input
 infile=$SUBJECTS_DIR/$tpid/$ldir/$input
-if [ ! -e $infile ]
-then
+if [ ! -e $infile ]; then
   echo "ERROR: $infile does not exist ..."
-	exit 1
+  exit 1
 fi
 bdir=$SUBJECTS_DIR/$base
-if [ ! -e $bdir ]
-then
+if [ ! -e $bdir ]; then
   echo "ERROR: $bdir does not exist ..."
-	exit 1
+  exit 1
 fi
 lta=$bdir/mri/transforms/${tp}_to_${base}.lta
-if [ ! -e $lta ]
-then
+if [ ! -e $lta ]; then
   echo "ERROR: $lta does not exist, make sure tp is part of this base ..."
-	exit 1
+  exit 1
 fi
 
 ofile=$bdir/$ldir/${tp}${longtxt}.$input
 
 case "$rt" in
-  "interpolate" )
+  "interpolate")
     cmd="mri_convert -at $lta"
-	  cmd="$cmd -rl $bdir/mri/$input"
-	  cmd="$cmd $infile $ofile" ;;
-	"nearest" )
+    cmd="$cmd -rl $bdir/mri/$input"
+    cmd="$cmd $infile $ofile"
+    ;;
+  "nearest")
     cmd="mri_convert -at $lta -rt $rt"
-	  cmd="$cmd -rl $bdir/mri/$input"
-	  cmd="$cmd $infile $ofile" ;;
-	"surface" )
-	  cmd="mris_transform $infile $lta $ofile";;
-   * )
-	  echo "ERROR: Reslice type: $rt not recognized"
-		exit 1 ;;
+    cmd="$cmd -rl $bdir/mri/$input"
+    cmd="$cmd $infile $ofile"
+    ;;
+  "surface")
+    cmd="mris_transform $infile $lta $ofile"
+    ;;
+  *)
+    echo "ERROR: Reslice type: $rt not recognized"
+    exit 1
+    ;;
 esac
 
-  echo $cmd
-	eval $cmd
+echo $cmd
+eval $cmd
